export const pageTexts = {
  es: {
    apiStagePokemon: "Básico",
    apiTrainer: "Partidario",
    cardName: "Nombre de la carta",
    hp: "PS",
    type: "Tipo",
    rarity: "Rareza",
    attacks: "Ataques",
    weaknesses: "Debilidades",
    description: "Descripción",
    moreInfo: "Más Información",
    home: "Inicio",
    cards: "Cartas",
    howToPlay: "Como Jugar",
    series: "Series",
    videogames: "Videojuegos",
    ods: "ODS",
    aboutUs: "Nosotros",
    odsAndTypes: "Objetivos de Desarrollo Sostenible (ODS) y Tipos Pokémon",
    odsRelatedTo: "ODS relacionada con",
    selectTypeToSeeOds: "Selecciona un tipo para ver su ODS relacionada",
    clickTypeToSeeOds: "Haz clic en un tipo de Pokémon para ver su ODS relacionada",
    footerTitle: "TCG Pokemon",
    footerDev: "2025 TCG Pokemon web. Desarrollado por Hanner Hernández, Alejando Vielma, Alejandro Rosas y Daniel Carreño",
    footerLegal: "Pokemon y todas las marcas relacionadas son propiedad de Nintendo, Game Freak y Creatures Inc",
    enjoyTitle: "¡Disfruta!",
    enjoyDescription: "Experimenta el JCC Pokémon de una manera completamente nueva, diseñada para dispositivos móviles. Disfruta de batallas rápidas y sencillas, colecciona cartas digitales únicas con",
    odsSectionTitle: "Pokémon y Objetivos de Desarrollo Sostenible",
    odsSectionSubtitle: "Descubre cómo cada tipo de Pokémon se relaciona con los ODS de las Naciones Unidas",
    odsSectionButton: "Ver todas las relaciones",
    deckGeneratorFilterAll: "Todo",
    deckGeneratorFilterPokemon: "Pokémon",
    deckGeneratorFilterTrainers: "Entrenadores",
    deckGeneratorFilterEnergy: "Energías",
    deckGeneratorConfigTitle: "Configuración",
    deckGeneratorAvailableExpansions: "Expansiones Disponibles",
    deckGeneratorLoading: "Generando...",
    deckGeneratorButtonGen: "Generar",
    deckGeneratorSummaryTitle: "Resumen de la Baraja:",
    deckGeneratorSummaryTotal: "Total de cartas:",
    deckGeneratorSummaryPokemon: "Pokémon",
    deckGeneratorSummaryTrainers: "Entrenadores",
    deckGeneratorSummaryEnergy: "Energías",
    deckGeneratorGeneratedTitle: "Baraja Generada",
    deckGeneratorNoDeck: "No se ha generado ninguna baraja aún.",
    deckGeneratorCardName: "Nombre:",
    deckGeneratorRulesTitle: "Reglas de Pokemon TCG",
    deckGeneratorRulesCompositionTitle: "Composición de la Baraja:",
    deckGeneratorRulesComposition1: "Exactamente 60 cartas",
    deckGeneratorRulesComposition2: "Máximo 4 copias de cualquier carta",
    deckGeneratorRulesComposition3: "Energías básicas sin límite",
    deckGeneratorRulesComposition4: "Al menos 1 Pokémon básico",
    deckGeneratorRulesDistributionTitle: "Distribución Típica:",
    deckGeneratorRulesDistribution1: "Pokémon: 15-20 cartas",
    deckGeneratorRulesDistribution2: "Entrenadores: 25-30 cartas",
    deckGeneratorRulesDistribution3: "Energías: 10-15 cartas",
    deckGeneratorRulesDistribution4: "Balance según estrategia",
    odsSectionCardAlt: "Tipo {type}",
    odsSectionOds: "ODS",
    odsSectionExplore: "¡Explora todos los tipos y aprende sobre los desafíos globales!",
    randomCardTitle: "Carta Pokémon aleatoria",
    randomCardLoading: "Cargando carta...",
    randomCardError: "No se pudo cargar la carta.",
    randomCardButton: "Obtener Otra Carta",
    randomCardTypeUnknown: "Tipo Desconocido",
    randomCardHP: "Puntos de Vida",
    randomCardAbility: "Habilidad",
    randomCardNoAbility: "Sin Habilidades",
    randomCardAbilityNoDesc: "Sin descripción disponible.",
    randomCardAttacks: "Ataques",
    randomCardNoAttacks: "Sin Ataques",
    randomCardWeaknesses: "Debilidades",
    randomCardNoWeaknesses: "Sin Debilidades",
    seriesSectionTitle: "Series",
    seriesSectionSubtitle: "Descubre nuestra colección de series",
    seriesSectionLoading: "Cargando series...",
    seriesSectionError: "Error al cargar las series",
    seriesSectionEmpty: "No hay series disponibles",
    seriesSectionEmptySubtitle: "Vuelve pronto para ver nuevo contenido",
    seriesSectionButton: "Ir a Series",
    tutorialSectionTitle: "Aprende a Jugar",
    tutorialSectionDescription: "Experimenta el JCC Pokémon de una manera completamente nueva, diseñada para dispositivos móviles. Disfruta de batallas rápidas y sencillas, colecciona cartas digitales únicas con",
    tutorialSectionButton: "Ir a Como Jugar",
    videogamesSectionTitle: "Videojuegos",
    videogamesSectionButton: "Ir a Videojuegos",
    advancedSearchTitle: "Busqueda Avanzada",
    advancedSearchSet: "Set",
    advancedSearchAllSets: "Todos",
    advancedSearchType: "Tipo",
    advancedSearchAllTypes: "Todos",
    advancedSearchRarity: "Rareza",
    advancedSearchAllRarities: "Todas",
    advancedSearchButton: "Buscar",
    cardStageDefault: "Pokémon",
    cardWeaknesses: "Debilidades:",
    cardNoWeaknesses: "Ninguna",
    cardExpansion: "Expansión",
    cardExpansionUnknown: "Desconocida",
    cardIllustrator: "Ilustrador",
    cardIllustratorUnknown: "Desconocido",
    cardOdsRelated: "ODS Relacionada",
    relatedCards: "Cartas Relacionadas",
    cardNotFound: "No se encontró la carta.",
    sortBy: "Ordenar por",
    sortById: "Id",
    sortByName: "Nombre",
    loadingCards: "Cargando cartas...",
    loadingMoreCards: "Cargando más cartas...",
    noCardFound: "No se ha encontrado la carta.",
    searchByName: "Buscar por nombre",
    searchBarPlaceholder: "Buscar...",
    showingCardsFromSet: "Mostrando cartas del set:",
    noCardsInSet: "No se encontraron cartas en el set",
    showingGeneralCards: "Mostrando cartas generales.",
    loadMore: "Cargar más",
    deckGeneratorTitle: "Generador de Barajas",
    deckGeneratorButton: "Ir a Generador de Barajas",
    instructionsLink: "Link de Instrucciones",
    setCardCount: "Nro de Cartas",
    setCardCountNA: "N/D",
    setReleaseDateNA: "Fecha no disponible",
    expansionsTitle: "Expansiones de",
    expansionsTitleDefault: "Pokémon Expansiones de Cartas",
    expansionsSearchPlaceholder: "Buscar expansiones...",
    expansionsSortBy: "Ordenar por",
    expansionsSortAlphabet: "Alfabeto",
    expansionsSortDate: "Fecha de emisión",
    expansionsSortCount: "Cantidad de Cartas",
    expansionsLoading: "Cargando expansiones...",
    expansionsError: "Error al cargar las expansiones.",
    expansionsNotFound: "No se encontraron expansiones.",
    aboutTitle: "Acerca de Nosotros",
    aboutSummaryTitle: "Resumen",
    aboutSummaryText: "Nuestra plataforma web está diseñada para revolucionar la experiencia de las catas de cartas TCG Pokémon. Ofrecemos un espacio digital donde los coleccionistas y jugadores pueden participar en catas virtuales, descubrir nuevas cartas, intercambiar con otros usuarios y mantenerse al día con las últimas novedades del mundo Pokémon. Con herramientas avanzadas de análisis, sistema de valoración en tiempo real y una comunidad activa, creamos la experiencia definitiva para los fanáticos de las cartas Pokémon.",
    aboutMembersTitle: "Integrantes",
    aboutTechTitle: "Tecnologías",
    aboutContactTitle: "Contacta con nosotros",
    aboutContactName: "Nombre",
    aboutContactEmail: "Correo electrónico",
    aboutContactTopic: "Asunto",
    aboutContactMessage: "Mensaje",
    aboutContactSend: "Enviar",
    serieCardLogoAlt: "Logo de {name}",
    serieCardNumExpansions: "Nro de Expansiones",
    seriesPageTitle: "Pokemon Series de Cartas",
    error404Title: "Creo que estás perdido",
    error404Description: "Lo siento, no pudimos encontrar esta página",
    error404Button: "Regresar al inicio",
    error500Title: "Error Inesperado",
    error500Description: "Nos encontramos trabajando en una solución",
    explore: "Explorar",
    odsPageTitle: "Tipos Pokémon y Objetivos de Desarrollo Sostenible",
    odsPageSubtitle: "Descubre cómo cada tipo de Pokémon se relaciona con los Objetivos de Desarrollo Sostenible de las Naciones Unidas",
    odsPageOds: "ODS",
    odsPageGoal: "Objetivo",
    odsPageSeeCards: "Ver cartas de",
    odsPageTypeCards: "Cartas de tipo",
    odsPageShowingTypeCards: "Mostrando cartas relacionadas con el tipo",
    odsPageLoadingCards: "Cargando cartas...",
    odsPageShowing12Of: "Mostrando 12 de",
    odsPageCards: "cartas",
    odsPageNoTypeCards: "No se encontraron cartas del tipo",
    odsPageWhatAreOds: "¿Qué son los Objetivos de Desarrollo Sostenible?",
    odsPageOdsAndPokemon: "Los ODS y Pokémon",
    odsPageOdsDescription1: "Los Objetivos de Desarrollo Sostenible (ODS) son 17 objetivos globales establecidos por las Naciones Unidas para lograr un futuro más sostenible para todos. En esta aplicación, hemos relacionado cada tipo de Pokémon con un ODS específico basándonos en las características y elementos que representan.",
    odsPageOdsDescription2: "Por ejemplo, el tipo Fuego se relaciona con el ODS 7 (Energía asequible y no contaminante) debido a su conexión con la energía y el fuego como fuente de poder.",
    odsPageLearnWhilePlaying: "Aprende mientras juegas",
    odsPageLearnDescription1: "Esta relación entre Pokémon y ODS te permite aprender sobre los objetivos de desarrollo sostenible de una manera divertida y accesible. Cada vez que veas un Pokémon de un tipo específico, podrás recordar el ODS relacionado y su importancia.",
    odsPageLearnDescription2: "¡Explora los diferentes tipos y descubre cómo cada uno contribuye a crear conciencia sobre los desafíos globales que enfrentamos!"
  },
  en: {
    deckGeneratorFilterAll: "All",
    deckGeneratorFilterPokemon: "Pokémon",
    deckGeneratorFilterTrainers: "Trainers",
    deckGeneratorFilterEnergy: "Energy",
    deckGeneratorConfigTitle: "Configuration",
    deckGeneratorAvailableExpansions: "Available Expansions",
    deckGeneratorLoading: "Generating...",
    deckGeneratorButtonGen: "Generate",
    deckGeneratorSummaryTitle: "Deck Summary:",
    deckGeneratorSummaryTotal: "Total cards:",
    deckGeneratorSummaryPokemon: "Pokémon",
    deckGeneratorSummaryTrainers: "Trainers",
    deckGeneratorSummaryEnergy: "Energy",
    deckGeneratorGeneratedTitle: "Generated Deck",
    deckGeneratorNoDeck: "No deck has been generated yet.",
    deckGeneratorCardName: "Name:",
    deckGeneratorRulesTitle: "Pokemon TCG Rules",
    deckGeneratorRulesCompositionTitle: "Deck Composition:",
    deckGeneratorRulesComposition1: "Exactly 60 cards",
    deckGeneratorRulesComposition2: "Maximum 4 copies of any card",
    deckGeneratorRulesComposition3: "Unlimited basic energies",
    deckGeneratorRulesComposition4: "At least 1 basic Pokémon",
    deckGeneratorRulesDistributionTitle: "Typical Distribution:",
    deckGeneratorRulesDistribution1: "Pokémon: 15-20 cards",
    deckGeneratorRulesDistribution2: "Trainers: 25-30 cards",
    deckGeneratorRulesDistribution3: "Energy: 10-15 cards",
    deckGeneratorRulesDistribution4: "Balance according to strategy",
    apiStagePokemon: "Basic",
    apiTrainer: "Supporter",
    cardName: "Card Name",
    hp: "HP",
    type: "Type",
    rarity: "Rarity",
    attacks: "Attacks",
    weaknesses: "Weaknesses",
    description: "Description",
    moreInfo: "More Info",
    home: "Home",
    cards: "Cards",
    howToPlay: "How to Play",
    series: "Series",
    videogames: "Videogames",
    ods: "SDGs",
    aboutUs: "About Us",
    odsAndTypes: "Sustainable Development Goals (SDGs) and Pokémon Types",
    odsRelatedTo: "SDG related to",
    selectTypeToSeeOds: "Select a type to see its related SDG",
    clickTypeToSeeOds: "Click on a Pokémon type to see its related SDG",
    footerTitle: "TCG Pokemon",
    footerDev: "2025 TCG Pokemon web. Developed by Hanner Hernández, Alejando Vielma, Alejandro Rosas and Daniel Carreño",
    footerLegal: "Pokemon and all related trademarks are property of Nintendo, Game Freak and Creatures Inc",
    enjoyTitle: "Enjoy!",
    enjoyDescription: "Experience the Pokémon TCG in a whole new way, designed for mobile devices. Enjoy fast and simple battles, and collect unique digital cards with",
    odsSectionTitle: "Pokémon and Sustainable Development Goals",
    odsSectionSubtitle: "Discover how each Pokémon type relates to the United Nations SDGs",
    odsSectionButton: "See all relationships",
    odsSectionCardAlt: "Type {type}",
    odsSectionOds: "SDG",
    odsSectionExplore: "Explore all types and learn about global challenges!",
    randomCardTitle: "Random Pokémon Card",
    randomCardLoading: "Loading card...",
    randomCardError: "Could not load the card.",
    randomCardButton: "Get Another Card",
    randomCardTypeUnknown: "Unknown Type",
    randomCardHP: "Hit Points",
    randomCardAbility: "Ability",
    randomCardNoAbility: "No Abilities",
    randomCardAbilityNoDesc: "No description available.",
    randomCardAttacks: "Attacks",
    randomCardNoAttacks: "No Attacks",
    randomCardWeaknesses: "Weaknesses",
    randomCardNoWeaknesses: "No Weaknesses",
    seriesSectionTitle: "Series",
    seriesSectionSubtitle: "Discover our series collection",
    seriesSectionLoading: "Loading series...",
    seriesSectionError: "Error loading series",
    seriesSectionEmpty: "No series available",
    seriesSectionEmptySubtitle: "Check back soon for new content",
    seriesSectionButton: "Go to Series",
    tutorialSectionTitle: "Learn to Play",
    tutorialSectionDescription: "Experience the Pokémon TCG in a whole new way, designed for mobile devices. Enjoy fast and simple battles, and collect unique digital cards.",
    tutorialSectionButton: "Go to How to Play",
    videogamesSectionTitle: "Videogames",
    videogamesSectionButton: "Go to Videogames",
    advancedSearchTitle: "Advanced Search",
    advancedSearchSet: "Set",
    advancedSearchAllSets: "All",
    advancedSearchType: "Type",
    advancedSearchAllTypes: "All",
    advancedSearchRarity: "Rarity",
    advancedSearchAllRarities: "All",
    advancedSearchButton: "Search",
    cardStageDefault: "Pokémon",
    cardWeaknesses: "Weaknesses:",
    cardNoWeaknesses: "None",
    cardExpansion: "Expansion",
    cardExpansionUnknown: "Unknown",
    cardIllustrator: "Illustrator",
    cardIllustratorUnknown: "Unknown",
    cardOdsRelated: "Related SDG",
    relatedCards: "Related Cards",
    cardNotFound: "Card not found.",
    sortBy: "Sort by",
    sortById: "Id",
    sortByName: "Name",
    loadingCards: "Loading cards...",
    loadingMoreCards: "Loading more cards...",
    noCardFound: "No card found.",
    searchByName: "Search by name",
    searchBarPlaceholder: "Search...",
    showingCardsFromSet: "Showing cards from set:",
    noCardsInSet: "No cards found in set",
    showingGeneralCards: "Showing general cards.",
    loadMore: "Load more",
    deckGeneratorTitle: "Deck Generator",
    deckGeneratorButton: "Go to Deck Generator",
    instructionsLink: "Instructions Link",
    setCardCount: "Card Count",
    setCardCountNA: "N/A",
    setReleaseDateNA: "Release date not available",
    expansionsTitle: "Expansions of",
    expansionsTitleDefault: "Pokémon Card Expansions",
    expansionsSearchPlaceholder: "Search expansions...",
    expansionsSortBy: "Sort by",
    expansionsSortAlphabet: "Alphabet",
    expansionsSortDate: "Release date",
    expansionsSortCount: "Card Count",
    expansionsLoading: "Loading expansions...",
    expansionsError: "Error loading expansions.",
    expansionsNotFound: "No expansions found.",
    aboutTitle: "About Us",
    aboutSummaryTitle: "Summary",
    aboutSummaryText: "Our web platform is designed to revolutionize the experience of Pokémon TCG card tastings. We offer a digital space where collectors and players can participate in virtual tastings, discover new cards, trade with other users, and stay up to date with the latest Pokémon news. With advanced analysis tools, real-time rating system, and an active community, we create the ultimate experience for Pokémon card fans.",
    aboutMembersTitle: "Members",
    aboutTechTitle: "Technologies",
    aboutContactTitle: "Contact Us",
    aboutContactName: "Name",
    aboutContactEmail: "Email",
    aboutContactTopic: "Subject",
    aboutContactMessage: "Message",
    aboutContactSend: "Send",
    serieCardLogoAlt: "Logo of {name}",
    serieCardNumExpansions: "Number of Expansions",
    seriesPageTitle: "Pokemon Card Series",
    error404Title: "I think you're lost",
    error404Description: "Sorry, we couldn't find this page",
    error404Button: "Back to home",
    error500Title: "Unexpected Error",
    error500Description: "We're working on a solution",
    explore: "Explore",
    odsPageTitle: "Pokémon Types and Sustainable Development Goals",
    odsPageSubtitle: "Discover how each Pokémon type relates to the United Nations Sustainable Development Goals",
    odsPageOds: "SDG",
    odsPageGoal: "Goal",
    odsPageSeeCards: "See cards of",
    odsPageTypeCards: "Cards of type",
    odsPageShowingTypeCards: "Showing cards related to type",
    odsPageLoadingCards: "Loading cards...",
    odsPageShowing12Of: "Showing 12 of",
    odsPageCards: "cards",
    odsPageNoTypeCards: "No cards found of type",
    odsPageWhatAreOds: "What are the Sustainable Development Goals?",
    odsPageOdsAndPokemon: "SDGs and Pokémon",
    odsPageOdsDescription1: "The Sustainable Development Goals (SDGs) are 17 global goals established by the United Nations to achieve a more sustainable future for all. In this app, we have linked each Pokémon type to a specific SDG based on the characteristics and elements they represent.",
    odsPageOdsDescription2: "For example, the Fire type is related to SDG 7 (Affordable and Clean Energy) due to its connection with energy and fire as a power source.",
    odsPageLearnWhilePlaying: "Learn while playing",
    odsPageLearnDescription1: "This relationship between Pokémon and SDGs allows you to learn about the sustainable development goals in a fun and accessible way. Every time you see a Pokémon of a specific type, you can remember the related SDG and its importance.",
    odsPageLearnDescription2: "Explore the different types and discover how each one helps raise awareness about the global challenges we face!"
  }
};